server:
  port: 8300
spring:
  application:
    name: justgo
  profiles:
    active: dev
  datasource:
    name: justgo_v_0_1
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.78.93.197:3306/justgo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver


  redis:
    host: 120.78.93.197
    port: 6379
    timeout: 100
    jedis:
      pool:
        max-active:  10

